### ISSUE TITLE
post setup failure

### ISSUE THREAD

**Issue by bishisht** [ioerror/blockfinder#96]
hello there. I have installed blockfinder but i am unable to continue the blockfinder -i thing. i am encountering an error. not much of a python coder here. 

Verifying RIR files...
Importing RIR files...
Traceback (most recent call last):
  File "/usr/local/bin/blockfinder", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/block_finder/blockfinder.py", line 1441, in main
    downloader_parser.parse_rir_files()
  File "/usr/local/lib/python2.7/dist-packages/block_finder/blockfinder.py", line 713, in parse_rir_files
    start_num = int(ipaddr.IPv4Address(entry['start']))
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 1399, in __init__
    self._check_packed_address(address, 4)
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 553, in _check_packed_address
    expected_len, self._version))
ipaddress.AddressValueError: '3.0.0.0' (len 7 != 4) is not permitted as an IPv4 address. Did you pass in a bytes (str in Python 2) instead of a unicode object?

**Comment by ioerror** [comment]
This should be fixed by using Python 3 with the latest git tip.
